// The build-time content index — menu rows without their bodies. Generated by
// vite/content-index.ts on every build and every dev-server change; keep these
// shapes in step with what that plugin emits.
declare module "virtual:content-index" {
  export interface WritingEntry {
    slug: string;
    file: string;
    title: string;
    date: string;
    year: string;
    readTime: string;
    tags: string[];
    excerpt: string;
    order: number;
  }
  export interface RecipeEntry {
    slug: string;
    file: string;
    title: string;
    note: string;
    serves: string;
  }
  export interface ExplicationEntry {
    slug: string;
    file: string;
  }
  export const writingIndex: WritingEntry[];
  export const recipeIndex: RecipeEntry[];
  export const explicationIndex: ExplicationEntry[];
}
